/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.TransictionsFunction;
import java.awt.Color;
import java.awt.image.ColorModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author John Victor
 */
public class FormTransictionFunction extends javax.swing.JFrame {

    private void carregarConjuntoEstados() {
        
        cboconjuntoestados.removeAllItems();
        cboconjuntoestados.addItem("...");
        
        ArrayList<String> conjuntoEstados = TransictionsFunction.conjuntoEstados;
        
        System.out.println(conjuntoEstados.size());
        
        for (String estado : conjuntoEstados) {
            cboconjuntoestados.addItem(estado);
        }
        
         
        

}
    
   

    public FormTransictionFunction() {
        initComponents();
        campoMensagem.setVisible(false);
        lblMensagem.setVisible(false);
        cboconjuntoestados.setBackground(Color.WHITE);
        cboconjuntoestadosdois.setBackground(Color.WHITE);
        cboalfabeto.setBackground(Color.WHITE);
        cboalfabetodois.setBackground(Color.WHITE);
        cbodirecao_parada.setBackground(Color.WHITE);
        carregarConjuntoEstados();

    }

    public void limparcbos() {

        cboconjuntoestados.setSelectedItem("...");
        cboconjuntoestadosdois.setSelectedItem("...");
        cboalfabeto.setSelectedItem("...");
        cboalfabetodois.setSelectedItem("...");
        cbodirecao_parada.setSelectedItem("...");
    }

    public void limpar_branco() {

        cboconjuntoestados.setBackground(Color.WHITE);
        cboconjuntoestadosdois.setBackground(Color.WHITE);
        cboalfabeto.setBackground(Color.WHITE);
        cboalfabetodois.setBackground(Color.WHITE);
        cbodirecao_parada.setBackground(Color.WHITE);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private int id = 0;

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin2 = new java.awt.Label();
        lblLogin3 = new java.awt.Label();
        txtlogin2 = new javax.swing.JTextField();
        lblLogin12 = new java.awt.Label();
        lblLogin13 = new java.awt.Label();
        txtlogin6 = new javax.swing.JTextField();
        titulo = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        lblfunc12 = new javax.swing.JLabel();
        painelPrincipal = new javax.swing.JPanel();
        campoMensagem = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();
        lblLogin10 = new java.awt.Label();
        titulo1 = new javax.swing.JPanel();
        cboalfabetodois = new javax.swing.JComboBox<>();
        cboconjuntoestadosdois = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbodirecao_parada = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cboconjuntoestados = new javax.swing.JComboBox<>();
        cboalfabeto = new javax.swing.JComboBox<>();
        lblid_controletransicao = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btncancelar2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btncancelar = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btncancelar3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btncancelar4 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btncancelar1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableTransictions = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        lblLogin2.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        lblLogin2.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin2.setText("Q");

        lblLogin3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblLogin3.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin3.setText("Numero de Estados");

        txtlogin2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtlogin2.setForeground(new java.awt.Color(109, 127, 145));
        txtlogin2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlogin2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlogin2FocusLost(evt);
            }
        });
        txtlogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlogin2ActionPerformed(evt);
            }
        });

        lblLogin12.setAlignment(java.awt.Label.RIGHT);
        lblLogin12.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        lblLogin12.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin12.setText("Γ");

        lblLogin13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblLogin13.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin13.setText("Alfabeto da fita");

        txtlogin6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtlogin6.setForeground(new java.awt.Color(109, 127, 145));
        txtlogin6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlogin6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlogin6FocusLost(evt);
            }
        });
        txtlogin6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlogin6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setBackground(new java.awt.Color(109, 127, 145));
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tituloMouseClicked(evt);
            }
        });
        titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        titulo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 280, 60));

        lblfunc12.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblfunc12.setForeground(new java.awt.Color(255, 255, 255));
        lblfunc12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfunc12.setText("JOHN'SOFTWARE");
        lblfunc12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblfunc12MouseEntered(evt);
            }
        });
        titulo.add(lblfunc12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 60));

        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        painelPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelPrincipalMouseClicked(evt);
            }
        });
        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoMensagem.setBackground(new java.awt.Color(255, 204, 204));
        campoMensagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMensagem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 51, 51));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setText("You have an error in you form");
        campoMensagem.add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 40));

        painelPrincipal.add(campoMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1190, 40));

        lblLogin10.setAlignment(java.awt.Label.RIGHT);
        lblLogin10.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        lblLogin10.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin10.setText("δ");
        painelPrincipal.add(lblLogin10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 30, 50));

        titulo1.setBackground(new java.awt.Color(255, 255, 255));
        titulo1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titulo1MouseClicked(evt);
            }
        });
        titulo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboalfabetodois.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cboalfabetodois.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "0", "1", "#" }));
        titulo1.add(cboalfabetodois, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 70, 40));

        cboconjuntoestadosdois.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cboconjuntoestadosdois.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Q1", "Q2", "Q3" }));
        titulo1.add(cboconjuntoestadosdois, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 70, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel3.setText(",");
        titulo1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 30, 40));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel4.setText("(");
        titulo1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 30, 50));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel5.setText(")");
        titulo1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 30, 50));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setText("=");
        titulo1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 30, 50));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel6.setText(",");
        titulo1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 30, 40));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel7.setText("(");
        titulo1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 30, 50));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel8.setText(")");
        titulo1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 30, 50));

        cbodirecao_parada.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbodirecao_parada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "R", "L", "S" }));
        titulo1.add(cbodirecao_parada, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 70, 40));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel9.setText(",");
        titulo1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 30, 40));

        cboconjuntoestados.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cboconjuntoestados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Q1", "Q2", "Q3" }));
        titulo1.add(cboconjuntoestados, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 70, 40));

        cboalfabeto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cboalfabeto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "0", "1", "#" }));
        titulo1.add(cboalfabeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 70, 40));

        lblid_controletransicao.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblid_controletransicao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblid_controletransicao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        lblid_controletransicao.setEnabled(false);
        titulo1.add(lblid_controletransicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 40));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("ID");
        titulo1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, -1));

        painelPrincipal.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 720, 80));

        jPanel1.setBackground(new java.awt.Color(109, 127, 145));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelar2.setBackground(new java.awt.Color(46, 204, 113));
        btncancelar2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btncancelar2.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncancelar2.setText("CADASTRAR");
        btncancelar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelar2MouseClicked(evt);
            }
        });
        jPanel1.add(btncancelar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 110));

        painelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 220, 110));

        jPanel3.setBackground(new java.awt.Color(192, 57, 43));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelar.setBackground(new java.awt.Color(109, 127, 145));
        btncancelar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncancelar.setText("EXCLUIR");
        btncancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelarMouseClicked(evt);
            }
        });
        jPanel3.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        painelPrincipal.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 220, 50));

        jPanel6.setBackground(new java.awt.Color(243, 156, 18));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelar3.setBackground(new java.awt.Color(109, 127, 145));
        btncancelar3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btncancelar3.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncancelar3.setText("LIMPAR");
        btncancelar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelar3MouseClicked(evt);
            }
        });
        jPanel6.add(btncancelar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        painelPrincipal.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 220, 50));

        jPanel4.setBackground(new java.awt.Color(241, 196, 15));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelar4.setBackground(new java.awt.Color(109, 127, 145));
        btncancelar4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btncancelar4.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncancelar4.setText("EDITAR");
        btncancelar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelar4MouseClicked(evt);
            }
        });
        jPanel4.add(btncancelar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        painelPrincipal.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 220, 50));

        jPanel23.setBackground(new java.awt.Color(109, 127, 145));
        painelPrincipal.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 10, 630));

        jPanel5.setBackground(new java.awt.Color(231, 76, 60));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelar1.setBackground(new java.awt.Color(109, 127, 145));
        btncancelar1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btncancelar1.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncancelar1.setText("CANCELAR");
        btncancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelar1MouseClicked(evt);
            }
        });
        jPanel5.add(btncancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        painelPrincipal.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 220, 50));

        TableTransictions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, "(Q1, 0) = ( Q1,0,R );"}
            },
            new String [] {
                "Id", "Funções de transição"
            }
        ));
        jScrollPane1.setViewportView(TableTransictions);

        painelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 360, 630));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel11.setText("Função de transição");
        painelPrincipal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 410, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/voltar.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        painelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 70, 70));

        getContentPane().add(painelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1190, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloMouseClicked

    private void lblfunc12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfunc12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblfunc12MouseEntered

    private void painelPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelPrincipalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_painelPrincipalMouseClicked

    private void txtlogin2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlogin2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlogin2FocusGained

    private void txtlogin2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlogin2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlogin2FocusLost

    private void txtlogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlogin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlogin2ActionPerformed

    private void txtlogin6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlogin6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlogin6FocusGained

    private void txtlogin6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlogin6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlogin6FocusLost

    private void txtlogin6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlogin6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlogin6ActionPerformed

    private void titulo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titulo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_titulo1MouseClicked

    private void btncancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelarMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_btncancelarMouseClicked

    private void btncancelar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelar2MouseClicked
        // TODO add your handling code here:

        limpar_branco();

        String conjuntoestado = cboconjuntoestados.getSelectedItem().toString();

        String conjuntoestadodois = cboconjuntoestadosdois.getSelectedItem().toString().trim();
        String alfabeto = cboalfabeto.getSelectedItem().toString().trim();
        String alfabetodois = cboalfabetodois.getSelectedItem().toString().trim();

        String direcao_parada = cbodirecao_parada.getSelectedItem().toString().trim();

        DefaultTableModel model = (DefaultTableModel) TableTransictions.getModel();

        if ((!conjuntoestado.equals("...")) && (!conjuntoestadodois.equals("...")) && (!alfabeto.equals("...")) && (!alfabetodois.equals("...") && (!direcao_parada.equals("...")))) {

            String concatena_transicao = ("(" + conjuntoestado + ", " + alfabeto + ") = (" + conjuntoestadodois + ", " + alfabetodois + "," + direcao_parada + ")");

            model.addRow(new Object[]{id++, concatena_transicao});

            limparcbos();

            lblMensagem.setText("Cadastro realizado com sucesso");
            campoMensagem.setBackground(new Color(204, 255, 204));
            lblMensagem.setForeground(new Color(39, 174, 96));
            campoMensagem.setVisible(true);
            lblMensagem.setVisible(true);

        } else {
            campoMensagem.setBackground(new Color(255, 204, 204));
            lblMensagem.setForeground(new Color(255, 51, 51));

            lblMensagem.setText("Preencha corretamente todos os campos");
            campoMensagem.setVisible(true);
            lblMensagem.setVisible(true);

            if (conjuntoestado.equals("...")) {
                cboconjuntoestados.grabFocus();
                cboconjuntoestados.setBackground(Color.red);
            } else if (alfabeto.equals("...")) {
                cboalfabeto.grabFocus();
                cboalfabeto.setBackground(Color.red);
            } else if (conjuntoestadodois.equals("...")) {
                cboconjuntoestadosdois.grabFocus();
                cboconjuntoestadosdois.setBackground(Color.red);
            } else if (alfabetodois.equals("...")) {
                cboalfabetodois.grabFocus();
                cboalfabetodois.setBackground(Color.red);
            } else if (direcao_parada.equals("...")) {
                cbodirecao_parada.grabFocus();
                cbodirecao_parada.setBackground(Color.red);
            }

        }


    }//GEN-LAST:event_btncancelar2MouseClicked

    private void btncancelar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelar3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelar3MouseClicked

    private void btncancelar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelar4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelar4MouseClicked

    private void btncancelar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelar1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        FormTuringMachine fm = new FormTuringMachine();
        fm.setLocationRelativeTo(null);
        fm.pack();
        fm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransictionFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransictionFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransictionFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransictionFunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                FormTransictionFunction fm = new FormTransictionFunction();
                fm.setLocationRelativeTo(null);
                fm.pack();
                fm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableTransictions;
    private javax.swing.JLabel btncancelar;
    private javax.swing.JLabel btncancelar1;
    private javax.swing.JLabel btncancelar2;
    private javax.swing.JLabel btncancelar3;
    private javax.swing.JLabel btncancelar4;
    private javax.swing.JPanel campoMensagem;
    private javax.swing.JComboBox<String> cboalfabeto;
    private javax.swing.JComboBox<String> cboalfabetodois;
    private javax.swing.JComboBox<String> cboconjuntoestados;
    private javax.swing.JComboBox<String> cboconjuntoestadosdois;
    private javax.swing.JComboBox<String> cbodirecao_parada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private java.awt.Label lblLogin10;
    private java.awt.Label lblLogin12;
    private java.awt.Label lblLogin13;
    private java.awt.Label lblLogin2;
    private java.awt.Label lblLogin3;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblfunc12;
    private javax.swing.JLabel lblid_controletransicao;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel titulo;
    private javax.swing.JPanel titulo1;
    private javax.swing.JTextField txtlogin2;
    private javax.swing.JTextField txtlogin6;
    // End of variables declaration//GEN-END:variables
}
