/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.TransictionsFunction;
import javax.swing.JOptionPane;
import java.util.Arrays;

/**
 *
 * @author John Victor
 */
public class FormTuringMachine extends javax.swing.JFrame {

    /**
     * Creates new form FormTuringMachine
     */
    public FormTuringMachine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    String [] conjuntoEstados;
    String [] conjuntoEstadosFinais;
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin2 = new java.awt.Label();
        lblLogin3 = new java.awt.Label();
        txtlogin2 = new javax.swing.JTextField();
        lblLogin12 = new java.awt.Label();
        lblLogin13 = new java.awt.Label();
        txtlogin6 = new javax.swing.JTextField();
        titulo = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        lblfunc12 = new javax.swing.JLabel();
        painelPrincipal = new javax.swing.JPanel();
        lblLogin = new java.awt.Label();
        campoMensagem = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblconjuntoestados = new java.awt.Label();
        txtconjuntoestados = new javax.swing.JTextField();
        lblalfabetoentrada = new java.awt.Label();
        txtalfabetoentrada = new javax.swing.JTextField();
        lblalfabetoFita = new java.awt.Label();
        txtalfabetofita = new javax.swing.JTextField();
        lblLogin8 = new java.awt.Label();
        lblLogin9 = new java.awt.Label();
        lblLogin10 = new java.awt.Label();
        lblLogin11 = new java.awt.Label();
        lblLogin18 = new java.awt.Label();
        lblLogin14 = new java.awt.Label();
        lblestadoinicial = new java.awt.Label();
        txtestadoinicial = new javax.swing.JTextField();
        lblLogin16 = new java.awt.Label();
        lblestadofinal = new java.awt.Label();
        txtconjuntoestadofinal = new javax.swing.JTextField();
        titulo2 = new javax.swing.JPanel();
        VAI1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cadfunction = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        lblLogin2.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        lblLogin2.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin2.setText("Q");

        lblLogin3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblLogin3.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin3.setText("Numero de Estados");

        txtlogin2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtlogin2.setForeground(new java.awt.Color(109, 127, 145));
        txtlogin2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlogin2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlogin2FocusLost(evt);
            }
        });
        txtlogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlogin2ActionPerformed(evt);
            }
        });

        lblLogin12.setAlignment(java.awt.Label.RIGHT);
        lblLogin12.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        lblLogin12.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin12.setText("Γ");

        lblLogin13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblLogin13.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin13.setText("Alfabeto da fita");

        txtlogin6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtlogin6.setForeground(new java.awt.Color(109, 127, 145));
        txtlogin6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlogin6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlogin6FocusLost(evt);
            }
        });
        txtlogin6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlogin6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setBackground(new java.awt.Color(109, 127, 145));
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tituloMouseClicked(evt);
            }
        });
        titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        titulo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 280, 60));

        lblfunc12.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblfunc12.setForeground(new java.awt.Color(255, 255, 255));
        lblfunc12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfunc12.setText("JOHN'SOFTWARE");
        lblfunc12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblfunc12MouseEntered(evt);
            }
        });
        titulo.add(lblfunc12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 60));

        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 70));

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        painelPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelPrincipalMouseClicked(evt);
            }
        });
        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setAlignment(java.awt.Label.RIGHT);
        lblLogin.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin.setText("Γ");
        painelPrincipal.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 30, 50));

        campoMensagem.setBackground(new java.awt.Color(255, 204, 204));
        campoMensagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMensagem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 51, 51));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setText("You have an error in you form");
        campoMensagem.add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 40));

        painelPrincipal.add(campoMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1050, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setText("TURING MACHINE");
        painelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 320, -1));

        lblconjuntoestados.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblconjuntoestados.setForeground(new java.awt.Color(109, 127, 145));
        lblconjuntoestados.setText("Conjunto de estados");
        painelPrincipal.add(lblconjuntoestados, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 370, 20));

        txtconjuntoestados.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtconjuntoestados.setForeground(new java.awt.Color(109, 127, 145));
        txtconjuntoestados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtconjuntoestadosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtconjuntoestadosFocusLost(evt);
            }
        });
        txtconjuntoestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconjuntoestadosActionPerformed(evt);
            }
        });
        painelPrincipal.add(txtconjuntoestados, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 330, 40));

        lblalfabetoentrada.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblalfabetoentrada.setForeground(new java.awt.Color(109, 127, 145));
        lblalfabetoentrada.setText("Alfabeto de entrada");
        painelPrincipal.add(lblalfabetoentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 370, 20));

        txtalfabetoentrada.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtalfabetoentrada.setForeground(new java.awt.Color(109, 127, 145));
        txtalfabetoentrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtalfabetoentradaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtalfabetoentradaFocusLost(evt);
            }
        });
        txtalfabetoentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalfabetoentradaActionPerformed(evt);
            }
        });
        painelPrincipal.add(txtalfabetoentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 330, 40));

        lblalfabetoFita.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblalfabetoFita.setForeground(new java.awt.Color(109, 127, 145));
        lblalfabetoFita.setText("Alfabeto da fita");
        painelPrincipal.add(lblalfabetoFita, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 370, 20));

        txtalfabetofita.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtalfabetofita.setForeground(new java.awt.Color(109, 127, 145));
        txtalfabetofita.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtalfabetofitaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtalfabetofitaFocusLost(evt);
            }
        });
        txtalfabetofita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalfabetofitaActionPerformed(evt);
            }
        });
        painelPrincipal.add(txtalfabetofita, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 330, 40));

        lblLogin8.setAlignment(java.awt.Label.RIGHT);
        lblLogin8.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        lblLogin8.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin8.setText("Q");
        painelPrincipal.add(lblLogin8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 40, 50));

        lblLogin9.setAlignment(java.awt.Label.RIGHT);
        lblLogin9.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        lblLogin9.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin9.setText("Σ");
        painelPrincipal.add(lblLogin9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 30, 50));

        lblLogin10.setAlignment(java.awt.Label.RIGHT);
        lblLogin10.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        lblLogin10.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin10.setText("δ");
        painelPrincipal.add(lblLogin10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 30, 60));

        lblLogin11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblLogin11.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin11.setText("Função de transição");
        painelPrincipal.add(lblLogin11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 370, 20));

        lblLogin18.setAlignment(java.awt.Label.RIGHT);
        lblLogin18.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        lblLogin18.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin18.setText("Q");
        painelPrincipal.add(lblLogin18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 30, 50));

        lblLogin14.setAlignment(java.awt.Label.RIGHT);
        lblLogin14.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        lblLogin14.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin14.setText("0");
        painelPrincipal.add(lblLogin14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, 50));

        lblestadoinicial.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblestadoinicial.setForeground(new java.awt.Color(109, 127, 145));
        lblestadoinicial.setText("Estado inicial");
        painelPrincipal.add(lblestadoinicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 370, 20));

        txtestadoinicial.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtestadoinicial.setForeground(new java.awt.Color(109, 127, 145));
        txtestadoinicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtestadoinicialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtestadoinicialFocusLost(evt);
            }
        });
        txtestadoinicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoinicialActionPerformed(evt);
            }
        });
        painelPrincipal.add(txtestadoinicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 330, 40));

        lblLogin16.setAlignment(java.awt.Label.RIGHT);
        lblLogin16.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        lblLogin16.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin16.setText("F");
        painelPrincipal.add(lblLogin16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 30, 50));

        lblestadofinal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblestadofinal.setForeground(new java.awt.Color(109, 127, 145));
        lblestadofinal.setText("Conjunto de estados finais");
        painelPrincipal.add(lblestadofinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 370, 20));

        txtconjuntoestadofinal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtconjuntoestadofinal.setForeground(new java.awt.Color(109, 127, 145));
        txtconjuntoestadofinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtconjuntoestadofinalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtconjuntoestadofinalFocusLost(evt);
            }
        });
        txtconjuntoestadofinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconjuntoestadofinalActionPerformed(evt);
            }
        });
        painelPrincipal.add(txtconjuntoestadofinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 330, 40));

        titulo2.setBackground(new java.awt.Color(109, 127, 145));
        titulo2.setForeground(new java.awt.Color(255, 255, 255));
        titulo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titulo2MouseClicked(evt);
            }
        });
        titulo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VAI1.setText("VAI");
        titulo2.add(VAI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 330, 40));

        jButton2.setText("STEP BY STEP");
        titulo2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 330, 40));

        painelPrincipal.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1050, 90));

        cadfunction.setBackground(new java.awt.Color(109, 127, 145));
        cadfunction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Funções de Transição");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        cadfunction.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 40));

        painelPrincipal.add(cadfunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 330, 40));

        getContentPane().add(painelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1050, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloMouseClicked

    private void lblfunc12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfunc12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblfunc12MouseEntered

    private void painelPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelPrincipalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_painelPrincipalMouseClicked

    private void txtconjuntoestadosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconjuntoestadosFocusGained
        // TODO add your handling code here:
  

    }//GEN-LAST:event_txtconjuntoestadosFocusGained

    private void txtconjuntoestadosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconjuntoestadosFocusLost
        // TODO add your handling code here:
        
        armazenarEstados();
//        
//        String cj_est_formt = Arrays.toString(conjuntoEstados);
        
       // for (int i = 0; i < conjuntoEstados.length; i++) {
            
           //conjunto 
          // if(conjuntoEstados[i].charAt(1) = "Q"){
               
           //}
       // }
        
       // cboconjuntoestados.removeAllItems();
        
      //  for (int i = 0; i < conjuntoEstados.length; i++) {
//            
//           
//          String cje = Arrays.toString(TransictionsFunction.conjuntoEstados);
//          JOptionPane.showMessageDialog(null, "estdo 1 => "+ TransictionsFunction.conjuntoEstados[0]
//                                               + "estados: \n\n"+cje
//                                               + "\n tamanho: " + TransictionsFunction.conjuntoEstados.length);
      //  }
      
      
      
    }//GEN-LAST:event_txtconjuntoestadosFocusLost

    private void txtconjuntoestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconjuntoestadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconjuntoestadosActionPerformed

    private void txtlogin2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlogin2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlogin2FocusGained

    private void txtlogin2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlogin2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlogin2FocusLost

    private void txtlogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlogin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlogin2ActionPerformed

    private void txtalfabetoentradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtalfabetoentradaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalfabetoentradaFocusGained

    private void txtalfabetoentradaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtalfabetoentradaFocusLost
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtalfabetoentradaFocusLost

    private void txtalfabetoentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalfabetoentradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalfabetoentradaActionPerformed

    private void txtalfabetofitaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtalfabetofitaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalfabetofitaFocusGained

    private void txtalfabetofitaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtalfabetofitaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalfabetofitaFocusLost

    private void txtalfabetofitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalfabetofitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalfabetofitaActionPerformed

    private void txtlogin6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlogin6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlogin6FocusGained

    private void txtlogin6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlogin6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlogin6FocusLost

    private void txtlogin6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlogin6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlogin6ActionPerformed

    private void txtestadoinicialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtestadoinicialFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoinicialFocusGained

    private void txtestadoinicialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtestadoinicialFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoinicialFocusLost

    private void txtestadoinicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoinicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoinicialActionPerformed

    private void txtconjuntoestadofinalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconjuntoestadofinalFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconjuntoestadofinalFocusGained

    private void txtconjuntoestadofinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconjuntoestadofinalFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconjuntoestadofinalFocusLost

    private void txtconjuntoestadofinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconjuntoestadofinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconjuntoestadofinalActionPerformed

    private void titulo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titulo2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_titulo2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
        armazenarEstados();
        
        FormTransictionFunction fm = new FormTransictionFunction();
         fm.setLocationRelativeTo(null);
         fm.pack();
         fm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    public void armazenarEstadosFinais() {
        String cj_est_f = txtconjuntoestados.getText();
        conjuntoEstadosFinais = cj_est_f.replaceAll("\\s", "").split(",");
        
        for (String ef : conjuntoEstadosFinais) {
           // if (e.charAt(0) == 'Q' || e.charAt(0) == 'q') {
                TransictionsFunction.conjuntoEstados.add(ef);
           // }
        }
    }
    
    public void armazenarEstados() {
        String cj_est = txtconjuntoestados.getText();
        conjuntoEstados = cj_est.replaceAll("\\s", "").split(",");
        
        for (String e : conjuntoEstados) {
            if (e.charAt(0) == 'Q' || e.charAt(0) == 'q') {
                TransictionsFunction.conjuntoEstados.add(e);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTuringMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTuringMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTuringMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTuringMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                                
                FormTuringMachine fm = new FormTuringMachine ();
                fm.setLocationRelativeTo(null);
                fm.pack();
                fm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VAI1;
    private javax.swing.JPanel cadfunction;
    private javax.swing.JPanel campoMensagem;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator3;
    private java.awt.Label lblLogin;
    private java.awt.Label lblLogin10;
    private java.awt.Label lblLogin11;
    private java.awt.Label lblLogin12;
    private java.awt.Label lblLogin13;
    private java.awt.Label lblLogin14;
    private java.awt.Label lblLogin16;
    private java.awt.Label lblLogin18;
    private java.awt.Label lblLogin2;
    private java.awt.Label lblLogin3;
    private java.awt.Label lblLogin8;
    private java.awt.Label lblLogin9;
    private javax.swing.JLabel lblMensagem;
    private java.awt.Label lblalfabetoFita;
    private java.awt.Label lblalfabetoentrada;
    private java.awt.Label lblconjuntoestados;
    private java.awt.Label lblestadofinal;
    private java.awt.Label lblestadoinicial;
    private javax.swing.JLabel lblfunc12;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel titulo;
    private javax.swing.JPanel titulo2;
    private javax.swing.JTextField txtalfabetoentrada;
    private javax.swing.JTextField txtalfabetofita;
    private javax.swing.JTextField txtconjuntoestadofinal;
    private javax.swing.JTextField txtconjuntoestados;
    private javax.swing.JTextField txtestadoinicial;
    private javax.swing.JTextField txtlogin2;
    private javax.swing.JTextField txtlogin6;
    // End of variables declaration//GEN-END:variables
}
